on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
# Need to learn more about ocaml and opam on windows, this fails with some cygwin and
# pkg-config errors I haven't pinned down
#         - windows-latest 
        ocaml-version:
          - 4.11.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v1

      - name: get ocaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1.1.5
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add . --yes --no-action

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
